// Copyright (c) 2026 Icewear Vezzo, Iced Up Records, Foundation Media,
// and Digital Currensy Inc. All rights reserved.
// Official play URL: https://blue-cloud-787.higgsfield.gg/
// You may read this file. Viewing it on GitHub is not a license to copy,
// ship, or brand a product as Icewear Vezzo / Rich Off Pints 4.
// See /NOTICE and /LICENSE.

export const STR = {
  title1: "ICEWEAR VEZZO", title2: "ROP 4",
  subtitle: "SIX MILES. ONE CITY. RUN YOUR RANK UP.",
  tapToStart: "TAP TO CONTINUE",
  startRun: "PLAY",
  garage: "GARAGE",
  howTo: "HOW TO PLAY",
  leaderboard: "LEADERBOARD",
  leaderboardTitle: "RUN LEADERBOARD",
  leaderboardScope: "WORLDWIDE · LIVE",
  noScores: "COMPLETE A RUN TO CLAIM THE FIRST GLOBAL SPOT",
  sound: "SOUND",
  soundOn: "SOUND ON",
  soundOff: "SOUND OFF",
  back: "BACK TO HOME",
  drive: "DRIVE THIS CAR",
  startGame: "START GAME",
  home: "HOME",
  myBest: "BEST",
  bestScore: "BEST SCORE",
  hudPints: "PINTS",
  hudMile: "MILE",
  remaining: "REMAINING",
  cash: "CASH",
  hudCombo: "COMBO",
  boost: "BOOST",
  shield: "SHIELD",
  pause: "PAUSE",
  boostReady: "PURPLE BOOST READY",
  pintFound: "PINT FOUND",
  ice: "+500 ICE",
  cashT: "+250 CASH",
  comboX2: "COMBO x2",
  nearMiss: "NEAR MISS",
  perfectDodge: "PERFECT DODGE",
  crash: "CRASH",
  shieldSaved: "CHAIN SHIELD",
  boostOn: "BOOST",
  wrecked: "RUN ENDED",
  runComplete: "SIX MILES COMPLETE",
  finalScore: "FINAL SCORE",
  completion: "COMPLETION",
  equippedVehicle: "EQUIPPED VEHICLE",
  rank: "RANK",
  statPints: "PINTS",
  statMiss: "NEAR MISSES",
  statDodge: "PERFECT DODGES",
  statTime: "TIME",
  statCombo: "MAX COMBO",
  statBoost: "BOOST USES",
  bonusFinish: "FINISH BONUS",
  bonusClean: "NO CRASH BONUS",
  bonusPints: "ALL PINTS BONUS",
  bonusCombo: "MAX COMBO BONUS",
  runItBack: "PLAY AGAIN",
  share: "SHARE RESULT",
  copyLink: "COPY LINK",
  downloadCard: "DOWNLOAD RESULT CARD",
  copied: "GAME LINK COPIED",
  downloaded: "RESULT CARD DOWNLOADED",
  shareFailed: "SHARE UNAVAILABLE — LINK COPIED",
  menu: "HOME",
  ranks: ["BRONZE PINT", "SILVER PINT", "GOLD PINT", "DIAMOND PINT", "ROP 4 LEGEND"],
  shareText: (rank, score, miles, pints, car) => `I just ran the full ${miles} miles in ICEWEAR VEZZO: ROP 4. Beat my rank. ${rank} · ${score.toLocaleString()} points · ${pints} pints · ${car}.`,
  howCards: [
    ["↔", "CHANGE LANES", "Swipe or use the arrow keys."],
    ["◆", "COLLECT", "Grab purple pints, ice, and cash."],
    ["◇", "DODGE TRAFFIC", "Near misses increase your reward."],
    ["⚡", "ACTIVATE BOOST", "Fill the purple meter and tap to boost."],
    ["⛓", "USE THE CHAIN SHIELD", "The chain blocks one crash."],
    ["6", "FINISH THE RUN", "Complete all six miles and post your rank."]
  ],
  garageCars: [
    { name: "ROP 4 WHITE", desc: "Album Edition", icon: "◇", req: 0, tint: null },
    { name: "BLACKED OUT", desc: "Night Spec", icon: "●", req: 1, tint: "#20242c" },
    { name: "PURPLE GHOST", desc: "Neon Spec", icon: "◆", req: 2, tint: "#7a2cff" },
    { name: "CHROME DREAM", desc: "Mirror Finish", icon: "✦", req: 3, tint: "#bfe6ff" },
    { name: "LEGEND PLATE", desc: "Collector Spec", icon: "▰", req: 4, tint: "#ffd47a" }
  ],
  lockedAt: r => "UNLOCK AT " + r,
  equipped: "EQUIPPED",
  tapEquip: "TAP TO EQUIP",
  loading: "LOADING DETROIT…",
  paused: "PAUSED",
  resume: "TAP TO RESUME",
  mile6: "FINAL STRETCH — 6 MILE RUSH"
};
